# Práctica 0: Soluciones de los ejercicios propuestos
# Inteligencia Artificial
# Grado en Ingeniería Informática - Ingeniería del Software
# Universidad de Sevilla

Los ejercicios que se plantean a continuación tienen como objetivo el practicar con los paquetes [Numpy](https://numpy.org) y [Pandas](https://pandas.pydata.org) de Python.

In [186]:
import numpy as np
# Configuramos Numpy para que no use notación científica al escribir números en coma flotante
np.set_printoptions(suppress=True)
import pandas as pd

Para ilustrar el funcionamiento pretendido de las funciones que se piden implementar, se hará uso del conjunto de datos acerca de coches incluido en el tema de aprendizaje automático que forma parte del contenido teórico de la asignatura.

```
   Origen     Cilindros  Potencia  Peso  Aceleración  Tipo de consumo
---------------------------------------------------------------------
Norteamérica      6        105     3613      16.5           Bajo
   Europa         4        76      2511      18.0           Bajo
   Europa         5        77      3530      20.1           Alto
   Japón          6        122     2807      13.5           Bajo
   Europa         4        90      2265      15.5           Alto
   Japón          4        70      1945      16.8           Alto
Norteamérica      8        145     3880      12.5           Bajo
Norteamérica      4        90      2670      16.0           Alto
Norteamérica      6        90      3211      17.0           Bajo
Norteamérica      8        198     4952      11.5           Bajo
```

La siguiente matriz guarda, entonces, los valores de los atributos, habiéndose codificado numéricamente el origen de los coches.

In [187]:
coches = np.array([[2, 6, 105, 3613, 16.5],
                   [0, 4, 76,  2511, 18.0],
                   [0, 5, 77,  3530, 20.1],
                   [1, 6, 122, 2807, 13.5],
                   [0, 4, 90,  2265, 15.5],
                   [1, 4, 70,  1945, 16.8],
                   [2, 8, 145, 3880, 12.5],
                   [2, 4, 90,  2670, 16.0],
                   [2, 6, 90,  3211, 17.0],
                   [2, 8, 198, 4952, 11.5]])

El siguiente vector, por su parte, guarda los valores del atributo objetivo.

In [188]:
tipo_de_consumo = np.array(['Bajo', 'Bajo', 'Alto', 'Bajo', 'Alto', 'Alto', 'Bajo', 'Alto', 'Bajo', 'Bajo'])

### Ejercicio 1

Definir una función `estima_prob_condicional_atributo` tal que:
- Reciba como argumentos:
  - Una matriz `atributo` con los valores, usando codificación _one-hot_, de un atributo discreto para todos los ejemplos de una determinada clase.
  - Una cantidad `k`, con valor 1 por defecto, de ejemplos virtuales adicionales a considerar para cada posible valor del atributo.
- Devuelva como resultado un vector con la estimación de máxima verosimilitud de la distribución de probabilidad del atributo condicionada a la clase.

### Solución del ejercicio 1

In [189]:
def estima_prob_condicional_atributo(atributo, k=1):
    frecuencias = atributo.sum(axis=0)
    frecuencias = frecuencias + k
    print("frecuencias", frecuencias)
    return frecuencias / frecuencias.sum()

#### Ejemplos del funcionamiento pretendido

In [190]:
# Estimación de máxima verosimilitud de la distribución de probabilidad del atributo cilindros
# condicionada a tipo de consumo alto, sin usar suavizado.

cilindros_consumo_alto = np.array([[0, 1, 0, 0],
                                   [1, 0, 0, 0],
                                   [1, 0, 0, 0],
                                   [1, 0, 0, 0]])

# las columnas del array anterior representan los posibles valores de cilindro
# índice 0 -> 4, 1 -> 5, 2 -> 6, 3 -> 8

# se trata de calcular en 1 única función todas las probabilidades de cilindro

estima_prob_condicional_atributo(cilindros_consumo_alto, k=0)
# array([0.75, 0.25, 0.  , 0.  ])

frecuencias [3 1 0 0]


array([0.75, 0.25, 0.  , 0.  ])

In [191]:
# Estimación de máxima verosimilitud de la distribución de probabilidad del atributo cilindros
# condicionada a tipo de consumo alto, usando suavizado de Laplace.

cilindros_consumo_alto = np.array([[0, 1, 0, 0],
                                   [1, 0, 0, 0],
                                   [1, 0, 0, 0],
                                   [1, 0, 0, 0]])
estima_prob_condicional_atributo(cilindros_consumo_alto)
# array([0.5  , 0.25 , 0.125, 0.125])

frecuencias [4 2 1 1]


array([0.5  , 0.25 , 0.125, 0.125])

In [192]:
# Estimación de máxima verosimilitud de la distribución de probabilidad del atributo cilindros
# condicionada a tipo de consumo bajo, sin usar suavizado.

cilindros_consumo_bajo = np.array([[0, 0, 1, 0],
                                   [1, 0, 0, 0],
                                   [0, 0, 1, 0],
                                   [0, 0, 0, 1],
                                   [0, 0, 1, 0],
                                   [0, 0, 0, 1]])
estima_prob_condicional_atributo(cilindros_consumo_bajo, k=0)
# array([0.16666667, 0.        , 0.5       , 0.33333333])

frecuencias [1 0 3 2]


array([0.16666667, 0.        , 0.5       , 0.33333333])

In [193]:
# Estimación de máxima verosimilitud de la distribución de probabilidad del atributo cilindros
# condicionada a tipo de consumo bajo, usando suavizado de Laplace.

cilindros_consumo_bajo = np.array([[0, 0, 1, 0],
                                   [1, 0, 0, 0],
                                   [0, 0, 1, 0],
                                   [0, 0, 0, 1],
                                   [0, 0, 1, 0],
                                   [0, 0, 0, 1]])
estima_prob_condicional_atributo(cilindros_consumo_bajo)
# array([0.2, 0.1, 0.4, 0.3])

frecuencias [2 1 4 3]


array([0.2, 0.1, 0.4, 0.3])

### Ejercicio 2

Definir una función `estima_prob_condicionales_atributo` tal que:
- Reciba como argumentos:
  - Una matriz `atributo` con los valores, usando codificación _one-hot_, de un atributo discreto para todos los ejemplos.
  - Un vector `objetivo` con los valores de un atributo objetivo discreto para todos los ejemplos.
  - Una cantidad `k`, con valor 1 por defecto, de ejemplos virtuales adicionales a considerar para cada posible valor del atributo.
- Devuelva como resultado una matriz que contenga las estimaciones de máxima verosimilitud de las distribuciones de probabilidad del atributo condicionadas a cada posible clase.

**Nota**: considérese el uso de la [función `unique`](https://numpy.org/doc/stable/reference/generated/numpy.unique.html) de Numpy para determinar los posibles valores del atributo objetivo.

### Solución del ejercicio 2

In [194]:
def estima_prob_condicionales_atributo(atributo, objetivo, k=1):
    clases = np.unique(objetivo)
    print("clases", clases)
    matriz_de_frecuencias = np.empty((clases.shape[0], atributo.shape[1]))
    for i, clase in enumerate(clases):
        # objetivo == clase crea una máscara booleana que selecciona las filas que cumplen
        atributo_en_clase = atributo[objetivo == clase]
        matriz_de_frecuencias[i] = estima_prob_condicional_atributo(atributo_en_clase, k)
    return matriz_de_frecuencias

#### Ejemplos del funcionamiento pretendido

In [195]:
# Estimaciones de máxima verosimilitud de las distribuciones de probabilidad del atributo origen
# condicionadas a cada tipo de consumo, sin usar suavizado.

origen = np.array([[0, 0, 1],
                   [1, 0, 0],
                   [1, 0, 0],
                   [0, 1, 0],
                   [1, 0, 0],
                   [0, 1, 0],
                   [0, 0, 1],
                   [0, 0, 1],
                   [0, 0, 1],
                   [0, 0, 1]])

# origen trae la informacion de la procedencia de todos los coches
# la funcion busca las probabilidades de cada procedencia segun el tipo de consumo (Y)

estima_prob_condicionales_atributo(origen, tipo_de_consumo, k=0)
# array([[0.5       , 0.25      , 0.25      ],
#        [0.16666667, 0.16666667, 0.66666667]])

clases ['Alto' 'Bajo']
frecuencias [2 1 1]
frecuencias [1 1 4]


array([[0.5       , 0.25      , 0.25      ],
       [0.16666667, 0.16666667, 0.66666667]])

In [196]:
# Estimaciones de máxima verosimilitud de las distribuciones de probabilidad del atributo origen
# condicionadas a cada tipo de consumo, usando suavizado de Laplace.

origen = np.array([[0, 0, 1],
                   [1, 0, 0],
                   [1, 0, 0],
                   [0, 1, 0],
                   [1, 0, 0],
                   [0, 1, 0],
                   [0, 0, 1],
                   [0, 0, 1],
                   [0, 0, 1],
                   [0, 0, 1]])
estima_prob_condicionales_atributo(origen, tipo_de_consumo)
# array([[0.42857143, 0.28571429, 0.28571429],
#        [0.22222222, 0.22222222, 0.55555556]])

clases ['Alto' 'Bajo']
frecuencias [3 2 2]
frecuencias [2 2 5]


array([[0.42857143, 0.28571429, 0.28571429],
       [0.22222222, 0.22222222, 0.55555556]])

In [197]:
# Estimaciones de máxima verosimilitud de las distribuciones de probabilidad del atributo cilindros
# condicionadas a cada tipo de consumo, sin usar suavizado.

cilindros = np.array([[0, 0, 1, 0],
                      [1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [1, 0, 0, 0],
                      [1, 0, 0, 0],
                      [0, 0, 0, 1],
                      [1, 0, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]])
estima_prob_condicionales_atributo(cilindros, tipo_de_consumo, k=0)
# array([[0.75      , 0.25      , 0.        , 0.        ],
#        [0.16666667, 0.        , 0.5       , 0.33333333]])

clases ['Alto' 'Bajo']
frecuencias [3 1 0 0]
frecuencias [1 0 3 2]


array([[0.75      , 0.25      , 0.        , 0.        ],
       [0.16666667, 0.        , 0.5       , 0.33333333]])

In [198]:
# Estimaciones de máxima verosimilitud de las distribuciones de probabilidad del atributo cilindros
# condicionadas a cada tipo de consumo, usando suavizado de Laplace.

cilindros = np.array([[0, 0, 1, 0],
                      [1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [1, 0, 0, 0],
                      [1, 0, 0, 0],
                      [0, 0, 0, 1],
                      [1, 0, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]])
estima_prob_condicionales_atributo(cilindros, tipo_de_consumo)
# array([[0.5  , 0.25 , 0.125, 0.125],
#        [0.2  , 0.1  , 0.4  , 0.3  ]])

clases ['Alto' 'Bajo']
frecuencias [4 2 1 1]
frecuencias [2 1 4 3]


array([[0.5  , 0.25 , 0.125, 0.125],
       [0.2  , 0.1  , 0.4  , 0.3  ]])

### Ejercicio 3

Definir una función `calcula_índice_de_Gini` tal que:
- Reciba como argumentos:
  - Un vector `objetivo` con los valores de un atributo objetivo discreto para un conjunto de ejemplos.
- Devuelva como resultado el índice de Gini, relativo al atributo objetivo, del conjunto de ejemplos.

### Solución del ejercicio 3

In [199]:
tipo_de_consumo

array(['Bajo', 'Bajo', 'Alto', 'Bajo', 'Alto', 'Alto', 'Bajo', 'Alto',
       'Bajo', 'Bajo'], dtype='<U4')

In [200]:
# formula 
def calcula_índice_de_Gini(objetivo):
    _, frecuencias = np.unique(objetivo, return_counts=True)
    print("frecuencias", frecuencias)
    frecuencias = frecuencias / frecuencias.sum()
    print("frecuencias normalizadas", frecuencias)
    return 1 - np.sum(np.square(frecuencias))  # O bien return 1 - np.sum(frecuencias ** 2)

#### Ejemplos del funcionamiento pretendido

In [201]:
calcula_índice_de_Gini(tipo_de_consumo)
# 0.48

frecuencias [4 6]
frecuencias normalizadas [0.4 0.6]


0.48

In [202]:
origen = coches[:, 0]
origen <= 0.5

array([False,  True,  True, False,  True, False, False, False, False,
       False])

In [203]:
calcula_índice_de_Gini(tipo_de_consumo[origen <= 0.5])
# 0.4444444444444444

frecuencias [2 1]
frecuencias normalizadas [0.66666667 0.33333333]


0.4444444444444444

In [204]:
origen = coches[:, 0]
calcula_índice_de_Gini(tipo_de_consumo[origen > 0.5])
# 0.40816326530612246

frecuencias [2 5]
frecuencias normalizadas [0.28571429 0.71428571]


0.40816326530612246

### Ejercicio 4

Definir una función `calcula_impurezas_promedio` tal que:
- Reciba como argumentos:
  - Un vector `atributo` con los valores de un atributo numérico para un conjunto de ejemplos.
  - Un vector `objetivo` con los valores de un atributo objetivo discreto para el mismo conjunto de ejemplos.
- Devuelva como resultado un vector con las impurezas promedio de todas las particiones inducidas por los umbrales candidatos considerados en el algoritmo CART.

### Solución del ejercicio 4

In [205]:
def calcula_impurezas_promedio(atributo, objetivo):
    # el atributo se emplea para encontrar los umbrales,
    # y con ellos encontrar las Y que son realmente las usadas en Gini
    total_ejemplos = atributo.shape[0]
    valores = np.unique(atributo)
    print("posibles valores", valores)
    umbrales = (valores[:-1] + valores[1:]) / 2
    impurezas_promedio = np.empty_like(umbrales)
    print("umbrales", umbrales)
    for i, umbral in enumerate(umbrales):
        print("\numbral", umbral)
        # selecciona las Y de los ejemplos que cumplen la condición de cada rama
        D_izq = objetivo[atributo <= umbral]
        print("izq", D_izq)
        # selecciona las Y de los ejemplos que cumplen la condición de cada rama
        D_der = objetivo[atributo > umbral]
        print("der", D_der)
        partición = (D_izq, D_der)
        índices_de_Gini = np.array([calcula_índice_de_Gini(D) for D in partición])
        print("índices de Gini", índices_de_Gini)
        tamaños_relativos = np.array([D.shape[0] for D in partición]) / total_ejemplos
        print("tamaños relativos", tamaños_relativos)
        impureza_promedio = np.average(índices_de_Gini, weights=tamaños_relativos)  # O bien np.sum(tamaños_relativos * índices_de_Gini)
        print("impureza promedio", impureza_promedio)
        impurezas_promedio[i] = impureza_promedio

    return impurezas_promedio

In [206]:
coches[:, 0]

array([2., 0., 0., 1., 0., 1., 2., 2., 2., 2.])

#### Ejemplos del funcionamiento pretendido

In [207]:
origen = coches[:, 0]
calcula_impurezas_promedio(origen, tipo_de_consumo)
# array([0.41904762, 0.4       ])

posibles valores [0. 1. 2.]
umbrales [0.5 1.5]

umbral 0.5
izq ['Bajo' 'Alto' 'Alto']
der ['Bajo' 'Bajo' 'Alto' 'Bajo' 'Alto' 'Bajo' 'Bajo']
frecuencias [2 1]
frecuencias normalizadas [0.66666667 0.33333333]
frecuencias [2 5]
frecuencias normalizadas [0.28571429 0.71428571]
índices de Gini [0.44444444 0.40816327]
tamaños relativos [0.3 0.7]
impureza promedio 0.419047619047619

umbral 1.5
izq ['Bajo' 'Alto' 'Bajo' 'Alto' 'Alto']
der ['Bajo' 'Bajo' 'Alto' 'Bajo' 'Bajo']
frecuencias [3 2]
frecuencias normalizadas [0.6 0.4]
frecuencias [1 4]
frecuencias normalizadas [0.2 0.8]
índices de Gini [0.48 0.32]
tamaños relativos [0.5 0.5]
impureza promedio 0.3999999999999999


array([0.41904762, 0.4       ])

In [208]:
# este es el ejemplo que obtiene el mejor umbral en la 1ra iteracion
# umbral 5.5
cilindros = coches[:, 1]
calcula_impurezas_promedio(cilindros, tipo_de_consumo)
# array([0.31666667, 0.16      , 0.4       ])

posibles valores [4. 5. 6. 8.]
umbrales [4.5 5.5 7. ]

umbral 4.5
izq ['Bajo' 'Alto' 'Alto' 'Alto']
der ['Bajo' 'Alto' 'Bajo' 'Bajo' 'Bajo' 'Bajo']
frecuencias [3 1]
frecuencias normalizadas [0.75 0.25]
frecuencias [1 5]
frecuencias normalizadas [0.16666667 0.83333333]
índices de Gini [0.375      0.27777778]
tamaños relativos [0.4 0.6]
impureza promedio 0.31666666666666665

umbral 5.5
izq ['Bajo' 'Alto' 'Alto' 'Alto' 'Alto']
der ['Bajo' 'Bajo' 'Bajo' 'Bajo' 'Bajo']
frecuencias [4 1]
frecuencias normalizadas [0.8 0.2]
frecuencias [5]
frecuencias normalizadas [1.]
índices de Gini [0.32 0.  ]
tamaños relativos [0.5 0.5]
impureza promedio 0.15999999999999992

umbral 7.0
izq ['Bajo' 'Bajo' 'Alto' 'Bajo' 'Alto' 'Alto' 'Alto' 'Bajo']
der ['Bajo' 'Bajo']
frecuencias [4 4]
frecuencias normalizadas [0.5 0.5]
frecuencias [2]
frecuencias normalizadas [1.]
índices de Gini [0.5 0. ]
tamaños relativos [0.8 0.2]
impureza promedio 0.4


array([0.31666667, 0.16      , 0.4       ])

In [209]:
potencia = coches[:, 2]
calcula_impurezas_promedio(potencia, tipo_de_consumo)
# array([0.4       , 0.475     , 0.41904762, 0.26666667, 0.34285714,
#        0.4       , 0.44444444])

posibles valores [ 70.  76.  77.  90. 105. 122. 145. 198.]
umbrales [ 73.   76.5  83.5  97.5 113.5 133.5 171.5]

umbral 73.0
izq ['Alto']
der ['Bajo' 'Bajo' 'Alto' 'Bajo' 'Alto' 'Bajo' 'Alto' 'Bajo' 'Bajo']
frecuencias [1]
frecuencias normalizadas [1.]
frecuencias [3 6]
frecuencias normalizadas [0.33333333 0.66666667]
índices de Gini [0.         0.44444444]
tamaños relativos [0.1 0.9]
impureza promedio 0.39999999999999997

umbral 76.5
izq ['Bajo' 'Alto']
der ['Bajo' 'Alto' 'Bajo' 'Alto' 'Bajo' 'Alto' 'Bajo' 'Bajo']
frecuencias [1 1]
frecuencias normalizadas [0.5 0.5]
frecuencias [3 5]
frecuencias normalizadas [0.375 0.625]
índices de Gini [0.5     0.46875]
tamaños relativos [0.2 0.8]
impureza promedio 0.475

umbral 83.5
izq ['Bajo' 'Alto' 'Alto']
der ['Bajo' 'Bajo' 'Alto' 'Bajo' 'Alto' 'Bajo' 'Bajo']
frecuencias [2 1]
frecuencias normalizadas [0.66666667 0.33333333]
frecuencias [2 5]
frecuencias normalizadas [0.28571429 0.71428571]
índices de Gini [0.44444444 0.40816327]
tamaños relati

array([0.4       , 0.475     , 0.41904762, 0.26666667, 0.34285714,
       0.4       , 0.44444444])

In [210]:
peso = coches[:, 3]
calcula_impurezas_promedio(peso, tipo_de_consumo)
# array([0.4       , 0.3       , 0.41904762, 0.31666667, 0.4       ,
#        0.45      , 0.34285714, 0.4       , 0.44444444])

posibles valores [1945. 2265. 2511. 2670. 2807. 3211. 3530. 3613. 3880. 4952.]
umbrales [2105.  2388.  2590.5 2738.5 3009.  3370.5 3571.5 3746.5 4416. ]

umbral 2105.0
izq ['Alto']
der ['Bajo' 'Bajo' 'Alto' 'Bajo' 'Alto' 'Bajo' 'Alto' 'Bajo' 'Bajo']
frecuencias [1]
frecuencias normalizadas [1.]
frecuencias [3 6]
frecuencias normalizadas [0.33333333 0.66666667]
índices de Gini [0.         0.44444444]
tamaños relativos [0.1 0.9]
impureza promedio 0.39999999999999997

umbral 2388.0
izq ['Alto' 'Alto']
der ['Bajo' 'Bajo' 'Alto' 'Bajo' 'Bajo' 'Alto' 'Bajo' 'Bajo']
frecuencias [2]
frecuencias normalizadas [1.]
frecuencias [2 6]
frecuencias normalizadas [0.25 0.75]
índices de Gini [0.    0.375]
tamaños relativos [0.2 0.8]
impureza promedio 0.30000000000000004

umbral 2590.5
izq ['Bajo' 'Alto' 'Alto']
der ['Bajo' 'Alto' 'Bajo' 'Bajo' 'Alto' 'Bajo' 'Bajo']
frecuencias [2 1]
frecuencias normalizadas [0.66666667 0.33333333]
frecuencias [2 5]
frecuencias normalizadas [0.28571429 0.71428571]
índice

array([0.4       , 0.3       , 0.41904762, 0.31666667, 0.4       ,
       0.45      , 0.34285714, 0.4       , 0.44444444])

In [211]:
aceleración = coches[:, 4]
calcula_impurezas_promedio(aceleración, tipo_de_consumo)
# array([0.44444444, 0.4       , 0.34285714, 0.45      , 0.48      ,
#        0.46666667, 0.47619048, 0.475     , 0.4       ])

posibles valores [11.5 12.5 13.5 15.5 16.  16.5 16.8 17.  18.  20.1]
umbrales [12.   13.   14.5  15.75 16.25 16.65 16.9  17.5  19.05]

umbral 12.0
izq ['Bajo']
der ['Bajo' 'Bajo' 'Alto' 'Bajo' 'Alto' 'Alto' 'Bajo' 'Alto' 'Bajo']
frecuencias [1]
frecuencias normalizadas [1.]
frecuencias [4 5]
frecuencias normalizadas [0.44444444 0.55555556]
índices de Gini [0.         0.49382716]
tamaños relativos [0.1 0.9]
impureza promedio 0.4444444444444444

umbral 13.0
izq ['Bajo' 'Bajo']
der ['Bajo' 'Bajo' 'Alto' 'Bajo' 'Alto' 'Alto' 'Alto' 'Bajo']
frecuencias [2]
frecuencias normalizadas [1.]
frecuencias [4 4]
frecuencias normalizadas [0.5 0.5]
índices de Gini [0.  0.5]
tamaños relativos [0.2 0.8]
impureza promedio 0.4

umbral 14.5
izq ['Bajo' 'Bajo' 'Bajo']
der ['Bajo' 'Bajo' 'Alto' 'Alto' 'Alto' 'Alto' 'Bajo']
frecuencias [3]
frecuencias normalizadas [1.]
frecuencias [4 3]
frecuencias normalizadas [0.57142857 0.42857143]
índices de Gini [0.         0.48979592]
tamaños relativos [0.3 0.7]
impurez

array([0.44444444, 0.4       , 0.34285714, 0.45      , 0.48      ,
       0.46666667, 0.47619048, 0.475     , 0.4       ])

### Ejercicio 5

Definir una función `obtén_vecinos_más_cercanos` tal que:
- Reciba como argumentos:
  - Un vector `ejemplo` con los valores de todos los atributos, numéricos, para un determinado ejemplo.
  - Una matriz `conjunto_de_ejemplos` con los valores de todos los atributos, numéricos, para cada ejemplo de un determinado conjunto.
  - Una cantidad `k` de vecinos a obtener.
- Devuelva como resultado una matriz con los `k` ejemplos de `conjunto_de_ejemplos` más cercanos a `ejemplo`, usando la distancia euclídea como medida de cercanía.

**Nota**: considérese el uso de la [función `argsort`](https://numpy.org/doc/stable/reference/generated/numpy.argsort.html) de Numpy para obtener los índices de los vecinos más cercanos.

### Solución del ejercicio 5

In [212]:
def obtén_vecinos_más_cercanos(ejemplo, conjunto_de_ejemplos, k):
    # Como la raíz cuadrada es una función creciente, para determinar los vecinos más cercanos basta
    # calcular las distancias euclídeas cuadráticas
    raices = np.square(conjunto_de_ejemplos - ejemplo)
    print("raices\n", raices)
    # axis=1 computa la suma de cada fila
    # se devuelve un array con el size de las filas
    distancias_euclídeas_cuadráticas = np.sum(raices, axis=1)
    print("distancias\n", distancias_euclídeas_cuadráticas)
    # busca los índices de las filas ordenados de menor a mayor distancia
    índices_vecinos_ordenados = np.argsort(distancias_euclídeas_cuadráticas)
    print("índices vecinos ordenados\n", índices_vecinos_ordenados)
    índices_vecinos_más_cercanos = índices_vecinos_ordenados[:k]
    return conjunto_de_ejemplos[índices_vecinos_más_cercanos]

### Ejemplos del funcionamiento pretendido

In [213]:
coches

array([[   2. ,    6. ,  105. , 3613. ,   16.5],
       [   0. ,    4. ,   76. , 2511. ,   18. ],
       [   0. ,    5. ,   77. , 3530. ,   20.1],
       [   1. ,    6. ,  122. , 2807. ,   13.5],
       [   0. ,    4. ,   90. , 2265. ,   15.5],
       [   1. ,    4. ,   70. , 1945. ,   16.8],
       [   2. ,    8. ,  145. , 3880. ,   12.5],
       [   2. ,    4. ,   90. , 2670. ,   16. ],
       [   2. ,    6. ,   90. , 3211. ,   17. ],
       [   2. ,    8. ,  198. , 4952. ,   11.5]])

In [214]:
coche = np.array([0, 4, 75, 2542, 17])
obtén_vecinos_más_cercanos(coche, coches, 3)
# array([[   0. ,    4. ,   76. , 2511. ,   18. ],
#        [   2. ,    4. ,   90. , 2670. ,   16. ],
#        [   1. ,    6. ,  122. , 2807. ,   13.5]])

raices
 [[      4.         4.       900.   1147041.         0.25]
 [      0.         0.         1.       961.         1.  ]
 [      0.         1.         4.    976144.         9.61]
 [      1.         4.      2209.     70225.        12.25]
 [      0.         0.       225.     76729.         2.25]
 [      1.         0.        25.    356409.         0.04]
 [      4.        16.      4900.   1790244.        20.25]
 [      4.         0.       225.     16384.         1.  ]
 [      4.         4.       225.    447561.         0.  ]
 [      4.        16.     15129.   5808100.        30.25]]
distancias
 [1147949.25     963.    976158.61   72451.25   76956.25  356435.04
 1795184.25   16614.    447794.   5823279.25]
índices vecinos ordenados
 [1 7 3 4 5 8 2 0 6 9]


array([[   0. ,    4. ,   76. , 2511. ,   18. ],
       [   2. ,    4. ,   90. , 2670. ,   16. ],
       [   1. ,    6. ,  122. , 2807. ,   13.5]])

In [215]:
coche = np.array([0, 4, 75, 2542, 17])
obtén_vecinos_más_cercanos(coche, coches, 5)
# array([[   0. ,    4. ,   76. , 2511. ,   18. ],
#        [   2. ,    4. ,   90. , 2670. ,   16. ],
#        [   1. ,    6. ,  122. , 2807. ,   13.5],
#        [   0. ,    4. ,   90. , 2265. ,   15.5],
#        [   1. ,    4. ,   70. , 1945. ,   16.8]])

raices
 [[      4.         4.       900.   1147041.         0.25]
 [      0.         0.         1.       961.         1.  ]
 [      0.         1.         4.    976144.         9.61]
 [      1.         4.      2209.     70225.        12.25]
 [      0.         0.       225.     76729.         2.25]
 [      1.         0.        25.    356409.         0.04]
 [      4.        16.      4900.   1790244.        20.25]
 [      4.         0.       225.     16384.         1.  ]
 [      4.         4.       225.    447561.         0.  ]
 [      4.        16.     15129.   5808100.        30.25]]
distancias
 [1147949.25     963.    976158.61   72451.25   76956.25  356435.04
 1795184.25   16614.    447794.   5823279.25]
índices vecinos ordenados
 [1 7 3 4 5 8 2 0 6 9]


array([[   0. ,    4. ,   76. , 2511. ,   18. ],
       [   2. ,    4. ,   90. , 2670. ,   16. ],
       [   1. ,    6. ,  122. , 2807. ,   13.5],
       [   0. ,    4. ,   90. , 2265. ,   15.5],
       [   1. ,    4. ,   70. , 1945. ,   16.8]])

### Ejercicio 6

Definir una función `codifica_atributo_discreto` tal que:
- Reciba como argumentos:
  - Una _Series_ de Pandas `atributo` con los valores de un atributo discreto para cada ejemplo de un determinado conjunto.
- Devuelva como resultado una **nueva** _Series_ de Pandas con esos valores codificados (en orden) numéricamente a partir de 0.

**Nota**: considérese el uso del [método `sort`](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.sort.html) de los _arrays_ de Numpy y de la [función `select`](https://numpy.org/doc/stable/reference/generated/numpy.select.html) de Numpy.

### Solución del ejercicio 6

In [216]:
def codifica_atributo_discreto(atributo):
    valores = atributo.unique()
    valores.sort()
    print("valores puros\n", [atributo == valor for valor in valores])
    
    valores_codificados = np.select(
        # A los indices que salgan a True
        [atributo == valor for valor in valores],
        # Se le asocia el valor que se pase en range()
        range(len(valores))
    )
    
    print("valores_codificados\n", valores_codificados)

    # se sigue usando el mismo index: atributo.index
    
    return pd.Series(valores_codificados, index=atributo.index)

# Otra posible forma de resolver el ejercicio

# def codifica_atributo_discreto(atributo):
#     atributo_codificado = pd.Series(0, index=atributo.index, dtype='int64')
#     valores = atributo.unique()
#     valores.sort()
#     for i, valor in enumerate(valores):
#         atributo_codificado[atributo == valor] = i
#     return atributo_codificado

#### Ejemplos del funcionamiento pretendido

In [217]:
origen = pd.Series(['Norteamérica', 'Europa', 'Europa', 'Japón', 'Europa', 'Japón',
                    'Norteamérica', 'Norteamérica', 'Norteamérica', 'Norteamérica'])
codifica_atributo_discreto(origen)
# 0    2
# 1    0
# 2    0
# 3    1
# 4    0
# 5    1
# 6    2
# 7    2
# 8    2
# 9    2
# dtype: int64

valores puros
 [0    False
1     True
2     True
3    False
4     True
5    False
6    False
7    False
8    False
9    False
dtype: bool, 0    False
1    False
2    False
3     True
4    False
5     True
6    False
7    False
8    False
9    False
dtype: bool, 0     True
1    False
2    False
3    False
4    False
5    False
6     True
7     True
8     True
9     True
dtype: bool]
valores_codificados
 [2 0 0 1 0 1 2 2 2 2]


0    2
1    0
2    0
3    1
4    0
5    1
6    2
7    2
8    2
9    2
dtype: int64

In [218]:
origen
# 0    Norteamérica
# 1          Europa
# 2          Europa
# 3           Japón
# 4          Europa
# 5           Japón
# 6    Norteamérica
# 7    Norteamérica
# 8    Norteamérica
# 9    Norteamérica
# dtype: object

0    Norteamérica
1          Europa
2          Europa
3           Japón
4          Europa
5           Japón
6    Norteamérica
7    Norteamérica
8    Norteamérica
9    Norteamérica
dtype: object

### Ejercicio 7

Definir una función `normaliza_atributo_numérico` tal que:
- Reciba como argumentos:
  - Una _Series_ de Pandas `atributo` con los valores de un atributo numérico para cada ejemplo de un determinado conjunto.
- Devuelva como resultado una **nueva** _Series_ de Pandas con esos valores normalizados al intervalo [0, 1].

### Solución del ejercicio 7

In [219]:
def normaliza_atributo_numérico(atributo):
    m = atributo.min()
    M = atributo.max()
    return (atributo - m) / (M - m)

#### Ejemplos del funcionamiento pretendido

In [220]:
potencia = pd.Series([105, 76, 77, 122, 90, 70, 145, 90, 90, 198])
normaliza_atributo_numérico(potencia)
# 0    0.273438
# 1    0.046875
# 2    0.054688
# 3    0.406250
# 4    0.156250
# 5    0.000000
# 6    0.585938
# 7    0.156250
# 8    0.156250
# 9    1.000000
# dtype: float64

0    0.273438
1    0.046875
2    0.054688
3    0.406250
4    0.156250
5    0.000000
6    0.585938
7    0.156250
8    0.156250
9    1.000000
dtype: float64

In [221]:
potencia
# 0    105
# 1     76
# 2     77
# 3    122
# 4     90
# 5     70
# 6    145
# 7     90
# 8     90
# 9    198
# dtype: int64

0    105
1     76
2     77
3    122
4     90
5     70
6    145
7     90
8     90
9    198
dtype: int64

### Ejercicio 8

Realizar las siguientes operaciones en el orden indicado:
1. Leer en un _DataFrame_ los datos de los coches desde el fichero `coches.csv`
2. Modificar el _DataFrame_ codificando numéricamente el atributo Origen.
3. Modificar el _DataFrame_ normalizando todos los atributos numéricos.

**Nota**: considérese el uso del [método `apply`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.apply.html) de los _DataFrames_ de Pandas.

#### Solución del ejercicio 8

In [222]:
coches = pd.read_csv('coches.csv')
atributos_discretos = ['Origen']
atributos_continuos = ['Cilindros', 'Potencia', 'Peso', 'Aceleración']
atributos = atributos_discretos + atributos_continuos
coches[atributos_discretos] = coches[atributos_discretos].apply(codifica_atributo_discreto)
coches[atributos] = coches[atributos].astype('float')
coches[atributos] = coches[atributos].apply(normaliza_atributo_numérico)
coches

# Otras posibles formas de resolver el ejercicio

# coches = pd.read_csv('coches.csv')
# coches['Origen'] = codifica_atributo_discreto(coches['Origen'])
# for nombre_atributo in coches.columns.drop('Tipo de consumo'):
#     coches[nombre_atributo] = coches[nombre_atributo].astype('float')
#     coches[nombre_atributo] = normaliza_atributo_numérico(coches[nombre_atributo])
# coches

# coches = pd.read_csv('coches.csv')
# coches['Origen'] = codifica_atributo_discreto(coches['Origen'])
# for nombre_atributo in coches:
#     if nombre_atributo != 'Tipo de consumo':
#         coches[nombre_atributo] = coches[nombre_atributo].astype('float')
#         coches[nombre_atributo] = normaliza_atributo_numérico(coches[nombre_atributo])
# coches

# Tras realizar las operaciones se debe tener el siguiente DataFrame:
#    Origen  Cilindros  Potencia      Peso  Aceleración  Tipo de consumo
# 0     1.0       0.50  0.273438  0.554706     0.581395             Bajo
# 1     0.0       0.00  0.046875  0.188227     0.755814             Bajo
# 2     0.0       0.25  0.054688  0.527103     1.000000             Alto
# 3     0.5       0.50  0.406250  0.286664     0.232558             Bajo
# 4     0.0       0.00  0.156250  0.106418     0.465116             Alto
# 5     0.5       0.00  0.000000  0.000000     0.616279             Alto
# 6     1.0       1.00  0.585938  0.643499     0.116279             Bajo
# 7     1.0       0.00  0.156250  0.241104     0.523256             Alto
# 8     1.0       0.50  0.156250  0.421018     0.639535             Bajo
# 9     1.0       1.00  1.000000  1.000000     0.000000             Bajo

valores puros
 [0    False
1     True
2     True
3    False
4     True
5    False
6    False
7    False
8    False
9    False
Name: Origen, dtype: bool, 0    False
1    False
2    False
3     True
4    False
5     True
6    False
7    False
8    False
9    False
Name: Origen, dtype: bool, 0     True
1    False
2    False
3    False
4    False
5    False
6     True
7     True
8     True
9     True
Name: Origen, dtype: bool]
valores_codificados
 [2 0 0 1 0 1 2 2 2 2]


,Origen,Cilindros,Potencia,Peso,Aceleración,Tipo de consumo
0,1.0,0.50,0.273438,0.554706,0.581395,Bajo
1,0.0,0.00,0.046875,0.188227,0.755814,Bajo
2,0.0,0.25,0.054688,0.527103,1.000000,Alto
3,0.5,0.50,0.406250,0.286664,0.232558,Bajo
4,0.0,0.00,0.156250,0.106418,0.465116,Alto
5,0.5,0.00,0.000000,0.000000,0.616279,Alto
6,1.0,1.00,0.585938,0.643499,0.116279,Bajo
7,1.0,0.00,0.156250,0.241104,0.523256,Alto
8,1.0,0.50,0.156250,0.421018,0.639535,Bajo
9,1.0,1.00,1.000000,1.000000,0.000000,Bajo
