# Práctica 0: Ejercicios propuestos
# Inteligencia Artificial
# Grado en Ingeniería Informática - Ingeniería del Software
# Universidad de Sevilla

Los ejercicios que se plantean a continuación tienen como objetivo el practicar con los paquetes [Numpy](https://numpy.org) y [Pandas](https://pandas.pydata.org) de Python.

In [1]:
import numpy as np
# Configuramos Numpy para que no use notación científica al escribir números en coma flotante
np.set_printoptions(suppress=True)
import pandas as pd

Para ilustrar el funcionamiento pretendido de las funciones que se piden implementar, se hará uso del conjunto de datos acerca de coches incluido en el tema de aprendizaje automático que forma parte del contenido teórico de la asignatura.

```
   Origen     Cilindros  Potencia  Peso  Aceleración  Tipo de consumo
---------------------------------------------------------------------
Norteamérica      6        105     3613      16.5           Bajo
   Europa         4        76      2511      18.0           Bajo
   Europa         5        77      3530      20.1           Alto
   Japón          6        122     2807      13.5           Bajo
   Europa         4        90      2265      15.5           Alto
   Japón          4        70      1945      16.8           Alto
Norteamérica      8        145     3880      12.5           Bajo
Norteamérica      4        90      2670      16.0           Alto
Norteamérica      6        90      3211      17.0           Bajo
Norteamérica      8        198     4952      11.5           Bajo
```

La siguiente matriz guarda, entonces, los valores de los atributos, habiéndose codificado numéricamente el origen de los coches.

In [2]:
coches = np.array([[2, 6, 105, 3613, 16.5],
                   [0, 4, 76,  2511, 18.0],
                   [0, 5, 77,  3530, 20.1],
                   [1, 6, 122, 2807, 13.5],
                   [0, 4, 90,  2265, 15.5],
                   [1, 4, 70,  1945, 16.8],
                   [2, 8, 145, 3880, 12.5],
                   [2, 4, 90,  2670, 16.0],
                   [2, 6, 90,  3211, 17.0],
                   [2, 8, 198, 4952, 11.5]])

El siguiente vector, por su parte, guarda los valores del atributo objetivo.

In [3]:
tipo_de_consumo = np.array(['Bajo', 'Bajo', 'Alto', 'Bajo', 'Alto', 'Alto', 'Bajo', 'Alto', 'Bajo', 'Bajo'])

### Ejercicio 1

Definir una función `estima_prob_condicional_atributo` tal que:
- Reciba como argumentos:
  - Una matriz `atributo` con los valores, usando codificación _one-hot_, de un atributo discreto para todos los ejemplos de una determinada clase.
  - Una cantidad `k`, con valor 1 por defecto, de ejemplos virtuales adicionales a considerar para cada posible valor del atributo.
- Devuelva como resultado un vector con la estimación de máxima verosimilitud de la distribución de probabilidad del atributo condicionada a la clase.

### Solución del ejercicio 1

In [ ]:

def estima_prob_condicional_atributo(atributo, k=1):
    # Aquí se implementaría la función de máxima verosimilitud para calcular la probabilidad de que los ejemplos virtuales pertenezcan a la clase 'Bajo' o 'Alto' en función de los coches de bajo consumo y alto consumo.
    N_c = atributo.shape[0] # filas
    X = atributo.shape[1] # columnas
    N_X_x_c = atributo.sum(axis=0) # suma de cada columna
    
    numerador = N_X_x_c + k
    denominador = N_c + (k * X)
    
    return numerador / denominador


atributos = ['Origen', 'Cilindros', 'Potencia', 'Peso', 'Aceleración']
# Cómo se construye una Matriz One-hot a partir de un array de etiquetas

# coches bajo consumo (el valor del atributo de la columna 5 es 'Bajo')
coches_bajo_consumo = [coches[i] for i in range(len(coches)) if tipo_de_consumo[i] == 'Bajo'] 

# coches alto consumo (el valor del atributo de la columna 5 es 'Alto')
coches_alto_consumo = [coches[i] for i in range(len(coches)) if tipo_de_consumo[i] == 'Alto']


P = {}

for atributo in atributos:
    idx = atributos.index(atributo)
    columna = [coche[idx] for coche in coches_bajo_consumo]
    one_hot = pd.get_dummies(columna, prefix=atributo)
    P[atributo] = estima_prob_condicional_atributo(one_hot.to_numpy(), k=1)

for atributo, probs in P.items():
    print(f"{atributo}: {probs}")

Origen: [0.22222222 0.22222222 0.55555556]
Cilindros: [0.22222222 0.44444444 0.33333333]
Potencia: [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]
Peso: [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]
Aceleración: [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]


#### Ejemplos del funcionamiento pretendido

In [ ]:
# Estimación de máxima verosimilitud de la distribución de probabilidad del atributo cilindros
# condicionada a tipo de consumo alto, sin usar suavizado.

cilindros_consumo_alto = np.array([[0, 1, 0, 0],
                                   [1, 0, 0, 0],
                                   [1, 0, 0, 0],
                                   [1, 0, 0, 0]])
estima_prob_condicional_atributo(cilindros_consumo_alto, k=0)
# array([0.75, 0.25, 0.  , 0.  ])

In [ ]:
# Estimación de máxima verosimilitud de la distribución de probabilidad del atributo cilindros
# condicionada a tipo de consumo alto, usando suavizado de Laplace.

cilindros_consumo_alto = np.array([[0, 1, 0, 0],
                                   [1, 0, 0, 0],
                                   [1, 0, 0, 0],
                                   [1, 0, 0, 0]])
estima_prob_condicional_atributo(cilindros_consumo_alto)
# array([0.5  , 0.25 , 0.125, 0.125])

In [ ]:
# Estimación de máxima verosimilitud de la distribución de probabilidad del atributo cilindros
# condicionada a tipo de consumo bajo, sin usar suavizado.

cilindros_consumo_bajo = np.array([[0, 0, 1, 0],
                                   [1, 0, 0, 0],
                                   [0, 0, 1, 0],
                                   [0, 0, 0, 1],
                                   [0, 0, 1, 0],
                                   [0, 0, 0, 1]])
estima_prob_condicional_atributo(cilindros_consumo_bajo, k=0)
# array([0.16666667, 0.        , 0.5       , 0.33333333])

In [ ]:
# Estimación de máxima verosimilitud de la distribución de probabilidad del atributo cilindros
# condicionada a tipo de consumo bajo, usando suavizado de Laplace.

cilindros_consumo_bajo = np.array([[0, 0, 1, 0],
                                   [1, 0, 0, 0],
                                   [0, 0, 1, 0],
                                   [0, 0, 0, 1],
                                   [0, 0, 1, 0],
                                   [0, 0, 0, 1]])
estima_prob_condicional_atributo(cilindros_consumo_bajo)
# array([0.2, 0.1, 0.4, 0.3])

### Ejercicio 2

Definir una función `estima_prob_condicionales_atributo` tal que:
- Reciba como argumentos:
  - Una matriz `atributo` con los valores, usando codificación _one-hot_, de un atributo discreto para todos los ejemplos.
  - Un vector `objetivo` con los valores de un atributo objetivo discreto para todos los ejemplos.
  - Una cantidad `k`, con valor 1 por defecto, de ejemplos virtuales adicionales a considerar para cada posible valor del atributo.
- Devuelva como resultado una matriz que contenga las estimaciones de máxima verosimilitud de las distribuciones de probabilidad del atributo condicionadas a cada posible clase.

**Nota**: considérese el uso de la [función `unique`](https://numpy.org/doc/stable/reference/generated/numpy.unique.html) de Numpy para determinar los posibles valores del atributo objetivo.

### Solución del ejercicio 2

#### Ejemplos del funcionamiento pretendido

In [ ]:
# Estimaciones de máxima verosimilitud de las distribuciones de probabilidad del atributo origen
# condicionadas a cada tipo de consumo, sin usar suavizado.

origen = np.array([[0, 0, 1],
                   [1, 0, 0],
                   [1, 0, 0],
                   [0, 1, 0],
                   [1, 0, 0],
                   [0, 1, 0],
                   [0, 0, 1],
                   [0, 0, 1],
                   [0, 0, 1],
                   [0, 0, 1]])
estima_prob_condicionales_atributo(origen, tipo_de_consumo, k=0)
# array([[0.5       , 0.25      , 0.25      ],
#        [0.16666667, 0.16666667, 0.66666667]])

In [ ]:
# Estimaciones de máxima verosimilitud de las distribuciones de probabilidad del atributo origen
# condicionadas a cada tipo de consumo, usando suavizado de Laplace.

origen = np.array([[0, 0, 1],
                   [1, 0, 0],
                   [1, 0, 0],
                   [0, 1, 0],
                   [1, 0, 0],
                   [0, 1, 0],
                   [0, 0, 1],
                   [0, 0, 1],
                   [0, 0, 1],
                   [0, 0, 1]])
estima_prob_condicionales_atributo(origen, tipo_de_consumo)
# array([[0.42857143, 0.28571429, 0.28571429],
#        [0.22222222, 0.22222222, 0.55555556]])

In [ ]:
# Estimaciones de máxima verosimilitud de las distribuciones de probabilidad del atributo cilindros
# condicionadas a cada tipo de consumo, sin usar suavizado.

cilindros = np.array([[0, 0, 1, 0],
                      [1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [1, 0, 0, 0],
                      [1, 0, 0, 0],
                      [0, 0, 0, 1],
                      [1, 0, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]])
estima_prob_condicionales_atributo(cilindros, tipo_de_consumo, k=0)
# array([[0.75      , 0.25      , 0.        , 0.        ],
#        [0.16666667, 0.        , 0.5       , 0.33333333]])

In [ ]:
# Estimaciones de máxima verosimilitud de las distribuciones de probabilidad del atributo cilindros
# condicionadas a cada tipo de consumo, usando suavizado de Laplace.

cilindros = np.array([[0, 0, 1, 0],
                      [1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [1, 0, 0, 0],
                      [1, 0, 0, 0],
                      [0, 0, 0, 1],
                      [1, 0, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]])
estima_prob_condicionales_atributo(cilindros, tipo_de_consumo)
# array([[0.5  , 0.25 , 0.125, 0.125],
#        [0.2  , 0.1  , 0.4  , 0.3  ]])

### Ejercicio 3

Definir una función `calcula_índice_de_Gini` tal que:
- Reciba como argumentos:
  - Un vector `objetivo` con los valores de un atributo objetivo discreto para un conjunto de ejemplos.
- Devuelva como resultado el índice de Gini, relativo al atributo objetivo, del conjunto de ejemplos.

### Solución del ejercicio 3

#### Ejemplos del funcionamiento pretendido

In [ ]:
calcula_índice_de_Gini(tipo_de_consumo)
# np.float64(0.48)

In [ ]:
origen = coches[:, 0]
calcula_índice_de_Gini(tipo_de_consumo[origen <= 0.5])
# np.float64(0.4444444444444444)

In [ ]:
origen = coches[:, 0]
calcula_índice_de_Gini(tipo_de_consumo[origen > 0.5])
# np.float64(0.40816326530612246)

### Ejercicio 4

Definir una función `calcula_impurezas_promedio` tal que:
- Reciba como argumentos:
  - Un vector `atributo` con los valores de un atributo numérico para un conjunto de ejemplos.
  - Un vector `objetivo` con los valores de un atributo objetivo discreto para el mismo conjunto de ejemplos.
- Devuelva como resultado un vector con las impurezas promedio de todas las particiones inducidas por los umbrales candidatos considerados en el algoritmo CART.

### Solución del ejercicio 4

#### Ejemplos del funcionamiento pretendido

In [ ]:
origen = coches[:, 0]
calcula_impurezas_promedio(origen, tipo_de_consumo)
# array([0.41904762, 0.4       ])

In [ ]:
cilindros = coches[:, 1]
calcula_impurezas_promedio(cilindros, tipo_de_consumo)
# array([0.31666667, 0.16      , 0.4       ])

In [ ]:
potencia = coches[:, 2]
calcula_impurezas_promedio(potencia, tipo_de_consumo)
# array([0.4       , 0.475     , 0.41904762, 0.26666667, 0.34285714,
#        0.4       , 0.44444444])

In [ ]:
peso = coches[:, 3]
calcula_impurezas_promedio(peso, tipo_de_consumo)
# array([0.4       , 0.3       , 0.41904762, 0.31666667, 0.4       ,
#        0.45      , 0.34285714, 0.4       , 0.44444444])

In [ ]:
aceleración = coches[:, 4]
calcula_impurezas_promedio(aceleración, tipo_de_consumo)
# array([0.44444444, 0.4       , 0.34285714, 0.45      , 0.48      ,
#        0.46666667, 0.47619048, 0.475     , 0.4       ])

### Ejercicio 5

Definir una función `obtén_vecinos_más_cercanos` tal que:
- Reciba como argumentos:
  - Un vector `ejemplo` con los valores de todos los atributos, numéricos, para un determinado ejemplo.
  - Una matriz `conjunto_de_ejemplos` con los valores de todos los atributos, numéricos, para cada ejemplo de un determinado conjunto.
  - Una cantidad `k` de vecinos a obtener.
- Devuelva como resultado una matriz con los `k` ejemplos de `conjunto_de_ejemplos` más cercanos a `ejemplo`, usando la distancia euclídea como medida de cercanía.

**Nota**: considérese el uso de la [función `argsort`](https://numpy.org/doc/stable/reference/generated/numpy.argsort.html) de Numpy para obtener los índices de los vecinos más cercanos.

### Solución del ejercicio 5

### Ejemplos del funcionamiento pretendido

In [ ]:
coche = np.array([0, 4, 75, 2542, 17])
obtén_vecinos_más_cercanos(coche, coches, 3)
# array([[   0. ,    4. ,   76. , 2511. ,   18. ],
#        [   2. ,    4. ,   90. , 2670. ,   16. ],
#        [   1. ,    6. ,  122. , 2807. ,   13.5]])

In [ ]:
coche = np.array([0, 4, 75, 2542, 17])
obtén_vecinos_más_cercanos(coche, coches, 5)
# array([[   0. ,    4. ,   76. , 2511. ,   18. ],
#        [   2. ,    4. ,   90. , 2670. ,   16. ],
#        [   1. ,    6. ,  122. , 2807. ,   13.5],
#        [   0. ,    4. ,   90. , 2265. ,   15.5],
#        [   1. ,    4. ,   70. , 1945. ,   16.8]])

### Ejercicio 6

Definir una función `codifica_atributo_discreto` tal que:
- Reciba como argumentos:
  - Una _Series_ de Pandas `atributo` con los valores de un atributo discreto para cada ejemplo de un determinado conjunto.
- Devuelva como resultado una **nueva** _Series_ de Pandas con esos valores codificados (en orden) numéricamente a partir de 0.

**Nota**: considérese el uso del [método `sort`](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.sort.html) de los _arrays_ de Numpy y de la [función `select`](https://numpy.org/doc/stable/reference/generated/numpy.select.html) de Numpy.

### Solución del ejercicio 6

#### Ejemplos del funcionamiento pretendido

In [ ]:
origen = pd.Series(['Norteamérica', 'Europa', 'Europa', 'Japón', 'Europa', 'Japón',
                    'Norteamérica', 'Norteamérica', 'Norteamérica', 'Norteamérica'])
codifica_atributo_discreto(origen)
# 0    2
# 1    0
# 2    0
# 3    1
# 4    0
# 5    1
# 6    2
# 7    2
# 8    2
# 9    2
# dtype: int64

In [ ]:
origen
# 0    Norteamérica
# 1          Europa
# 2          Europa
# 3           Japón
# 4          Europa
# 5           Japón
# 6    Norteamérica
# 7    Norteamérica
# 8    Norteamérica
# 9    Norteamérica
# dtype: object

### Ejercicio 7

Definir una función `normaliza_atributo_numérico` tal que:
- Reciba como argumentos:
  - Una _Series_ de Pandas `atributo` con los valores de un atributo numérico para cada ejemplo de un determinado conjunto.
- Devuelva como resultado una **nueva** _Series_ de Pandas con esos valores normalizados al intervalo [0, 1].

### Solución del ejercicio 7

#### Ejemplos del funcionamiento pretendido

In [ ]:
potencia = pd.Series([105, 76, 77, 122, 90, 70, 145, 90, 90, 198])
normaliza_atributo_numérico(potencia)
# 0    0.273438
# 1    0.046875
# 2    0.054688
# 3    0.406250
# 4    0.156250
# 5    0.000000
# 6    0.585938
# 7    0.156250
# 8    0.156250
# 9    1.000000
# dtype: float64

In [ ]:
potencia
# 0    105
# 1     76
# 2     77
# 3    122
# 4     90
# 5     70
# 6    145
# 7     90
# 8     90
# 9    198
# dtype: int64

### Ejercicio 8

Realizar las siguientes operaciones en el orden indicado:
1. Leer en un _DataFrame_ los datos de los coches desde el fichero `coches.csv`
2. Modificar el _DataFrame_ codificando numéricamente el atributo Origen.
3. Modificar el _DataFrame_ normalizando todos los atributos numéricos.

**Nota**: considérese el uso del [método `apply`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.apply.html) de los _DataFrames_ de Pandas.

#### Solución del ejercicio 8

In [ ]:


# Tras realizar las operaciones se debe tener el siguiente DataFrame:
#    Origen  Cilindros  Potencia      Peso  Aceleración  Tipo de consumo
# 0     1.0       0.50  0.273438  0.554706     0.581395             Bajo
# 1     0.0       0.00  0.046875  0.188227     0.755814             Bajo
# 2     0.0       0.25  0.054688  0.527103     1.000000             Alto
# 3     0.5       0.50  0.406250  0.286664     0.232558             Bajo
# 4     0.0       0.00  0.156250  0.106418     0.465116             Alto
# 5     0.5       0.00  0.000000  0.000000     0.616279             Alto
# 6     1.0       1.00  0.585938  0.643499     0.116279             Bajo
# 7     1.0       0.00  0.156250  0.241104     0.523256             Alto
# 8     1.0       0.50  0.156250  0.421018     0.639535             Bajo
# 9     1.0       1.00  1.000000  1.000000     0.000000             Bajo